project:
  type: website
  output-dir: docs

website:
  title: "Galen Sheely"
  body-footer: | 
    ![](/img/banner1.jpg)
  sidebar: false
  navbar:
    right:
      - href: index.qmd
        icon: card-heading
        text: About
      - href: publications.qmd
        icon: journals
        text: Publications & Projects
      - icon: file-earmark-pdf-fill
        text: CV
        href: "https://www.dropbox.com/scl/fi/hgypy1mposyxt8dxnlnlf/Sheely_CV.pdf?rlkey=9jpb3nxwzkd20kze0k3agfifc&dl=0"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
