---
title: Publications and Projects
toc: false
---

## Publications:

- Sheely, Galen. 2024. [“Moving the Electoral Goalposts: State and Local Strategies of Electoral Intervention in the U.S.”](https://www.dropbox.com/scl/fi/h3sm3p7s7mrbgml4vf2rq/GMS_EM-WP_Manuscript-Revised.pdf?rlkey=5vv3e3h7w9r0ifw21ywvocp1z&dl=0) Electoral Studies (Forthcoming).

- Freedman, Paul, Jennifer L. Lawless, and Galen Sheely. 2022. [Election 2021: Democracy, Voter Confidence, and Electoral Integrity in Virginia.](https://www.dropbox.com/scl/fi/llka8yuzkud6fgxb6s4sz/Election-2021-Report_Final-KARSH.pdf?rlkey=b3xd4z4o0nsxy0f0nr3uijklr&dl=0) 2022. University of Virginia: Karsh Institute of Democracy.



## Working Projects:

-   *Getting Blogged Down: Tracing Illiberal Political thought Through Blogs Using Text Analysis*

    -   Presented at Annual Midwest Political Science Association Conference 2023, to be presented at American Political Science Association Annual Meeting 2023.

-   *State Electoral Entrepreneurs: Motivated Election Administration*

    -   To be presented at American Political Science Association Annual Meeting 2023.
